title: Australian Globus Community
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: Australian Globus Community
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "Australian Globus Community resources (managed by AARNet)"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@3.0.0

exclude:
  - vendor
  - Gemfile

defaults:
# Define here page metadata attributes for all pages at once or on specific directories. More information: https://jekyllrb.com/docs/configuration/front-matter-defaults/
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      sidebar: "main"
  - scope:
      path: "globus-community-au"
      type: "pages"
    values:
      permalink: /globus-community-au/:basename
  - scope:
      path: "code"
      type: "pages"
    values:
      permalink: /code/:basename

theme_variables:
  git_host: GitHub
  back_to_top: true
  privacy_statement_url: /privacy
  github_buttons:
    position: top
    edit_me: true
    open_issue: true
    history: true
  headings:
    related-pages: Related pages
    more-information-tiles: More information
    resource-table-all: Tools and resources on this page
    resource-table-all-collapse: false
    affiliation-tiles-page: Affiliations
    contributor-minitiles-page: Contributors
  toc:
    min_headings: 2
    headings: 'h2'
  topnav:
    theme: light
    brand_logo: "assets/img/logo_globus-solid.svg"
    github: true
    twitter: false
  theme_color: 0d6efd
  fonts:
    - url towards a font

plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick

# --- Missing in gitlab: ---
# github:
#   repository_url: https://github.com/ELIXIR-Belgium/elixir-toolkit-theme
#   source:
#     branch: main

